### ISSUE TITLE
No `CharEvent` received

### ISSUE THREAD

**Issue by Pentalimbed** [Pentalimbed/catmenu#2]
https://github.com/Pentalimbed/catmenu/blob/74709daefda919834ad2f6d9a2287cdf90f2f5a3/src/input.cpp#L293

The input `a_events` are never of the type `RE::INPUT_EVENT_TYPE::kChar`, which makes imgui unable to receive character inputs.

This is unexpected because the hook is the same as [here](https://github.com/Pentalimbed/skyrim-community-shaders/blob/20c72e083783457a7e53c4c8c476221aa09f363c/src/Hooks.cpp#L408) and [here](https://github.com/ersh1/OpenAnimationReplacer/blob/786b286ffc0f680d9cbe3e70f59c5cf2387d3017/src/Hooks.h#L158).

**Comment by FlayaN** [comment]
Fixed here https://github.com/Pentalimbed/catmenu/commit/54b06ea9801a77302c3f811f3d4b5718feaf8230
